CREATE TABLE records(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    text TEXT NOT NULL,
    title CHAR(50) NOT NULL,
    favorites BOOLEAN NOT NULL DEFAULT FALSE,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
